version: "3.8"

services:
  postgres_online_test_db:
    container_name: postgres_online_test_db
    image: "postgres:15-alpine"
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_POSTGRES}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: personal_project_online_test
    volumes:
      - type: volume
        source: postgres_volume_compose
        target: "/var/lib/postgresql/data"
        read_only: false
    networks:
      - project_network

  postgres_online_test_db_test:
    container_name: postgres_online_test_db_test
    image: "postgres:15-alpine"
    ports:
      - "5402:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_POSTGRES}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: test_personal_project_online_test
    networks:
      - project_network
  online-test:
    container_name: online-test
    build:
      context: .
      dockerfile: Dockerfile
    image: "ahmadsgr39/app_online_test:1.0.0"
    ports:
      - "9999:8080"
    environment:
      # Provide your own .env file
      SIGNATURE_KEY: "U6xOqiivo/fsQWEFhGQ1osn28gfjPticu9eW1VNapNY="
      ACTIVE_PROFILE: prod
      DB_HOST: postgres_online_test_db
      DB_USERNAME_POSTGRES: ${DB_USERNAME_POSTGRES}
      DB_PASSWORD: ${DB_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - postgres_online_test_db
      - postgres_online_test_db_test
    restart: always
    networks:
      - project_network

volumes:
  postgres_volume_compose:
    name: postgres_volume_compose

networks:
  project_network:
    name: project_network
    driver: bridge