spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5400/test_personal_project_online_test
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 2MB
      max-request-size: 10MB

server:
  port: 8080

SIGNATURE_KEY: U6xOqiivo/fsQWEFhGQ1osn28gfjPticu9eW1VNapNY=

SEEDER_TOKEN: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjgxYTE5ZGQ4LWJjMDgtNDM4ZC05YzBjLTk3MWMxOWRmN2YyMSIsInJvbGUiOiJBZG1pbiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY5MzA1OTc5NiwiZXhwIjoxNzI0NTk1Nzk2fQ.Axxvy8mAsCQn57Lobhe8we2ZIwaRigCNirbEfVQLnvA