spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5400/personal_project_online_test
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 2MB
      max-request-size: 10MB

server:
  port: 8080

SIGNATURE_KEY: ${SIGNATURE_KEY}