spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5400/test_personal_project_online_test
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 5MB
  task:
    scheduling:
      pool:
        size: 2

server:
  port: 9999

BASE_URL: http://localhost:9999/api/v1/

CLIENT_BASE_URL: http://localhost:9999/api/v1/

SIGNATURE_KEY: U6xOqiivo/fsQWEFhGQ1osn28gfjPticu9eW1VNapNY=